### PR TITLE
🚀 DEPLOYMENT 06-03-19

### PR DESCRIPTION
**Pull request by astroash**
**Changes:**
- update dependencies
- change to migration file creation script
- update way to create demo & test data
- add reporting scripts
- trim payloads
- record active day events for users

Partnered PR: https://github.com/TwinePlatform/twine-visitor/pull/703

### CODE REVIEW

**Comment by astroash** [comment]
@eliascodes do you mind looking at the conflict. I think it's from one of your PRs

**Comment by astroash** [comment]
#366 should not be in this PR. This is showing from rebasing deployment last week

**Comment by eliascodes** [comment]
#366 _should_ be in this PR. Do you mean #336?

**Comment by eliascodes** [comment]
> do you mind looking at the conflict. I think it's from one of your PRs

It's actually a result of your hotfixes #359 and #360. I don't know which user ID is the right one.

**Comment by astroash** [comment]
@eliascodes I've partnered this with TwinePlatform/twine-visitor#703 as i do not think there are many client facing changes.

Do you think any other manual testing needs to be done?

**Pull request merged**
