### PR TITLE
🔧 add temp-dash server to cors settings

### LINKED ISSUE #206: login enforces restricted privilage for TWINE_ADMIN
https://github.com/TwinePlatform/twine-api/blob/41dc3947a58483633d4424614369328b16ba403e/src/api/v1/users/login.ts#L13-L23

All TWINE_ADMIN permissions are `full`, but they are forced to to `restricted` due to the current check on origin.

@eliascodes did you have a plan for how this would work? If not I can look into options.

### PR DESCRIPTION
**Pull request by astroash**
fixes #206

### CODE REVIEW

**Comment by eliascodes** [comment]
Also pls remember to tag your PRs and issues with the right project 🙂

**Comment by astroash** [comment]
@eliascodes do we want to host this on a subdomain, or use the netlify address?

**Comment by astroash** [comment]
> Also pls remember to tag your PRs and issues with the right project 🙂

Do we want to follow a specific convention for this? I'm cross referencing commits fairly adhoc at the moment.

**Comment by eliascodes** [comment]
> @eliascodes do we want to host this on a subdomain, or use the netlify address?

Shall we put it on `admin.twine-together.com`?

> Do we want to follow a specific convention for this? I'm cross referencing commits fairly adhoc at the moment.

Just choose the project that is relevant to the work you're currently doing. I guess this currently falls "between" projects because it wasn't in the roadmap before, but IMO Stage 3 is fine.

**Comment by astroash** [comment]
> Shall we put it on admin.twine-together.com?

👍🏽

**Pull request merged**
